name: Black Formatting

on:
  push:
    branches:
      - main

jobs:
  format:
    name: Format with Black
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black
        run: black .
      
      - name: Configure Git
        run: |
          git config --global user.name "${GIT_AUTHOR_NAME}"
          git config --global user.email "${GIT_AUTHOR_EMAIL}"

      - name: Amend Previous Commit With Same Commit Message
        run: |
          git commit --amend --no-edit
          git push --force-with-lease